/******************************************************/
/************* Date : 10/03/2024 **********************/
/************* File Name : DIO_Configuration **********/
/************* Version : v1.0 *************************/
/************* Author : Mohamed Elhossien *************/
/******************************************************/

#ifndef DIO_CONF_H_
#define DIO_CONF_H_

/**************************************************************/
/***** CONFIGURATIONS FOR THE INITIAL DIRECTION OF PORTS ******/
/********* OPTIONS: 1- DIO_PIN_OUTPUT *************************/
/*****************  2- DIO_PIN_INPUT  *************************/
/**************************************************************/

/***** CONFIGURATIONS FOR THE INITIAL DIRECTION OF PORTA ******/
#define DIO_PORTA_PIN0_INIT_DIREC		DIO_PIN_INPUT
#define DIO_PORTA_PIN1_INIT_DIREC		DIO_PIN_INPUT
#define DIO_PORTA_PIN2_INIT_DIREC		DIO_PIN_INPUT
#define DIO_PORTA_PIN3_INIT_DIREC		DIO_PIN_INPUT
#define DIO_PORTA_PIN4_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN5_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN6_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN7_INIT_DIREC		DIO_PIN_OUTPUT

/***** CONFIGURATIONS FOR THE INITIAL DIRECTION OF PORTB ******/
#define DIO_PORTB_PIN0_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN1_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN2_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN3_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN4_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN5_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN6_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN7_INIT_DIREC	    DIO_PIN_OUTPUT

/***** CONFIGURATIONS FOR THE INITIAL DIRECTION OF PORTC ******/
#define DIO_PORTC_PIN0_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN1_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN2_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN3_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN4_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN5_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN6_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN7_INIT_DIREC	    DIO_PIN_OUTPUT

/***** CONFIGURATIONS FOR THE INITIAL DIRECTION OF PORTD ******/
#define DIO_PORTD_PIN0_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN1_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN2_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN3_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN4_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN5_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN6_INIT_DIREC		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN7_INIT_DIREC	    DIO_PIN_OUTPUT


/**************************************************************/
/******* CONFIGURATIONS FOR THE INITIAL VALUE OF PORTS ********/
/********* OPTIONS: 1- DIO_PIN_HIGH ***************************/
/*****************  2- DIO_PIN_LOW  ***************************/
/*****************  3- DIO_PIN_PULLUP *************************/
/*****************  4- DIO_PIN_NOPULLUP ***********************/
/**************************************************************/

/******* CONFIGURATIONS FOR THE INITIAL VALUE OF PORTA ********/
#define DIO_PORTA_PIN0_INIT_VALUE		DIO_PIN_PULLUP
#define DIO_PORTA_PIN1_INIT_VALUE		DIO_PIN_PULLUP
#define DIO_PORTA_PIN2_INIT_VALUE		DIO_PIN_PULLUP
#define DIO_PORTA_PIN3_INIT_VALUE		DIO_PIN_PULLUP
#define DIO_PORTA_PIN4_INIT_VALUE		DIO_PIN_HIGH
#define DIO_PORTA_PIN5_INIT_VALUE		DIO_PIN_HIGH
#define DIO_PORTA_PIN6_INIT_VALUE		DIO_PIN_HIGH
#define DIO_PORTA_PIN7_INIT_VALUE		DIO_PIN_HIGH

/******* CONFIGURATIONS FOR THE INITIAL VALUE OF PORTB ********/
#define DIO_PORTB_PIN0_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN1_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN2_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN3_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN4_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN5_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN6_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTB_PIN7_INIT_VALUE	    DIO_PIN_LOW

/******* CONFIGURATIONS FOR THE INITIAL VALUE OF PORTC ********/
#define DIO_PORTC_PIN0_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN1_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN2_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN3_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN4_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN5_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN6_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTC_PIN7_INIT_VALUE	    DIO_PIN_LOW

/******* CONFIGURATIONS FOR THE INITIAL VALUE OF PORTD ********/
#define DIO_PORTD_PIN0_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN1_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN2_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN3_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN4_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN5_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN6_INIT_VALUE		DIO_PIN_LOW
#define DIO_PORTD_PIN7_INIT_VALUE       DIO_PIN_LOW

#endif /* DIO_CONF_H_ */
